// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/doom1bk.tga
gfx/env/doom1dn.tga
gfx/env/doom1ft.tga
gfx/env/doom1lf.tga
gfx/env/doom1rt.tga
gfx/env/doom1up.tga
ins2/bipod.spr
ins2/firemodes.spr
ins2/wpn/c4/hit1.ogg
ins2/wpn/c4/hit2.ogg
ins2/wpn/c4/hit3.ogg
ins2/wpn/tnt/fuse.ogg
ins2/wpn/tnt/hit1.ogg
ins2/wpn/tnt/hit2.ogg
ins2/wpn/tnt/hit3.ogg
ins2/wpn1024.spr
maps/albulena.gmr
maps/albulena.gsr
maps/albulena.res
models/ins2/ammo/mags.mdl
models/ins2/shells/12g_b.mdl
models/ins2/shells/12g_g.mdl
models/ins2/shells/300wm.mdl
models/ins2/shells/303.mdl
models/ins2/shells/308.mdl
models/ins2/shells/30cal.mdl
models/ins2/shells/45acp.mdl
models/ins2/shells/46x30.mdl
models/ins2/shells/50ae.mdl
models/ins2/shells/50bmg.mdl
models/ins2/shells/545.mdl
models/ins2/shells/556.mdl
models/ins2/shells/556ap.mdl
models/ins2/shells/762.mdl
models/ins2/shells/762t.mdl
models/ins2/shells/762x33.mdl
models/ins2/shells/762x54.mdl
models/ins2/shells/763.mdl
models/ins2/shells/792k.mdl
models/ins2/shells/792x57.mdl
models/ins2/shells/9mm.mdl
models/ins2/shells/9x18.mdl
models/ins2/shells/9x39.mdl
models/ins2/wpn/ftm2/p_m2.mdl
models/ins2/wpn/ftm2/v_m2.mdl
models/ins2/wpn/ftm2/w_m2.mdl
models/turkroaches/cliff5.mdl
models/turkroaches/env.mdl
models/turkroaches/p_kick.mdl
models/turkroaches/pi_tree.mdl
models/turkroaches/roach.mdl
models/turkroaches/scaredroach.mdl
models/turkroaches/v_kick.mdl
models/turkroaches/w_kick.mdl
scripts/maps/albulena/albulena.as
scripts/maps/albulena/ins2/base.as
scripts/maps/albulena/ins2/explo/weapon_ins2m2.as
scripts/maps/albulena/ins2/proj/proj_ins2flame.as
sound/ins2/wpn/ammo.ogg
sound/ins2/wpn/bdraw1.ogg
sound/ins2/wpn/bdraw2.ogg
sound/ins2/wpn/bdraw3.ogg
sound/ins2/wpn/chrg/det1.ogg
sound/ins2/wpn/chrg/det2.ogg
sound/ins2/wpn/chrg/det3.ogg
sound/ins2/wpn/chrg/wdet1.ogg
sound/ins2/wpn/chrg/wdet2.ogg
sound/ins2/wpn/chrg/wdet3.ogg
sound/ins2/wpn/empty.ogg
sound/ins2/wpn/fdraw1.ogg
sound/ins2/wpn/fdraw2.ogg
sound/ins2/wpn/fdraw3.ogg
sound/ins2/wpn/fdraw4.ogg
sound/ins2/wpn/fdraw5.ogg
sound/ins2/wpn/fdraw6.ogg
sound/ins2/wpn/ftm2/cap1.ogg
sound/ins2/wpn/ftm2/cap2.ogg
sound/ins2/wpn/ftm2/cap3.ogg
sound/ins2/wpn/ftm2/capon.ogg
sound/ins2/wpn/ftm2/empty.ogg
sound/ins2/wpn/ftm2/end.ogg
sound/ins2/wpn/ftm2/loop.ogg
sound/ins2/wpn/ftm2/start.ogg
sound/ins2/wpn/ftm2/trgoff.ogg
sound/ins2/wpn/ftm2/trgon.ogg
sound/ins2/wpn/gdraw1.ogg
sound/ins2/wpn/gdraw2.ogg
sound/ins2/wpn/gdraw3.ogg
sound/ins2/wpn/gdraw4.ogg
sound/ins2/wpn/gren/det1.ogg
sound/ins2/wpn/gren/det2.ogg
sound/ins2/wpn/gren/det3.ogg
sound/ins2/wpn/gren/hit1.ogg
sound/ins2/wpn/gren/hit2.ogg
sound/ins2/wpn/gren/hit3.ogg
sound/ins2/wpn/gren/hit4.ogg
sound/ins2/wpn/gren/wdet1.ogg
sound/ins2/wpn/gren/wdet2.ogg
sound/ins2/wpn/gren/wdet3.ogg
sound/ins2/wpn/hitb1.ogg
sound/ins2/wpn/hitb2.ogg
sound/ins2/wpn/hitb3.ogg
sound/ins2/wpn/hitb4.ogg
sound/ins2/wpn/hitw1.ogg
sound/ins2/wpn/hitw2.ogg
sound/ins2/wpn/hitw3.ogg
sound/ins2/wpn/hitw4.ogg
sound/ins2/wpn/in1.ogg
sound/ins2/wpn/in2.ogg
sound/ins2/wpn/in3.ogg
sound/ins2/wpn/knife/hitb1.ogg
sound/ins2/wpn/knife/hitb2.ogg
sound/ins2/wpn/knife/hitb3.ogg
sound/ins2/wpn/knife/hitb4.ogg
sound/ins2/wpn/knife/swg1.ogg
sound/ins2/wpn/knife/swg2.ogg
sound/ins2/wpn/knife/swg3.ogg
sound/ins2/wpn/knife/swg4.ogg
sound/ins2/wpn/out1.ogg
sound/ins2/wpn/out2.ogg
sound/ins2/wpn/out3.ogg
sound/ins2/wpn/pdraw1.ogg
sound/ins2/wpn/pdraw2.ogg
sound/ins2/wpn/pdraw3.ogg
sound/ins2/wpn/pdraw4.ogg
sound/ins2/wpn/pdraw5.ogg
sound/ins2/wpn/rckt/det1.ogg
sound/ins2/wpn/rckt/det2.ogg
sound/ins2/wpn/rckt/det3.ogg
sound/ins2/wpn/rckt/wdet1.ogg
sound/ins2/wpn/rckt/wdet2.ogg
sound/ins2/wpn/rckt/wdet3.ogg
sound/ins2/wpn/rdraw1.ogg
sound/ins2/wpn/rdraw2.ogg
sound/ins2/wpn/rdraw3.ogg
sound/player/pl_slosh1.wav
sound/player/pl_slosh2.wav
sound/player/pl_slosh3.wav
sound/turkmusic/albania.ogg
sound/turkmusic/albulena.mp3
sound/turkmusic/hmmm.wav
sound/turkmusic/roach_walk.ogg
sound/turkmusic/scratch.ogg
sound/turkmusic/turkwin.mp3
sound/turkmusic/wood_break.ogg
sprites/albulena/albania.spr
sprites/albulena/dordemartinovic.spr
sprites/ammo_m2ft.spr
sprites/bubble.spr
sprites/crosshairs.spr
sprites/ins2/exp//weapon_ins2m2.txt
sprites/ins2/exp/ammo_m2ft.spr
sprites/ins2/faexplode1.spr
sprites/ins2/fireball1.spr
sprites/ins2/fireball2.spr
sprites/ins2/flame1.spr
sprites/ins2/flame2.spr
sprites/ins2/flame3.spr
sprites/ins2/flame4.spr
sprites/ins2/flame5.spr
sprites/ins2/steam1.spr
sprites/ins2/wpn1024.spr
sprites/laserbeam.spr
sprites/steam1.spr
sprites/watersmoke.spr
sprites/wep_smoke_01.spr
sprites/WXplo1.spr
sprites/zerogxplode.spr
turkroaches.wad
