// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/HKbk.tga
gfx/env/HKdn.tga
gfx/env/HKft.tga
gfx/env/HKlf.tga
gfx/env/HKrt.tga
gfx/env/HKup.tga
models/blackhawk/monster/AX.mdl
models/blackhawk/monster/bloodlurker.mdl
models/blackhawk/monster/bonecrab.mdl
models/blackhawk/monster/ghost.mdl
models/blackhawk/monster/helldog.mdl
models/blackhawk/monster/hunter.mdl
models/blackhawk/monster/peon.mdl
models/blackhawk/monster/zombie.mdl
models/blackhawk/monster/zombie_barney.mdl
models/blackhawk/monster/zombie_soldier.mdl
models/blackhawk/static/potplant.mdl
models/blackhawk/static/uplant1.mdl
models/blackhawk/static/uplant2.mdl
models/blackhawk/static/uplant3.mdl
models/blackhawk/weapons/p_9mmhandgun.mdl
models/blackhawk/weapons/p_fist.mdl
models/blackhawk/weapons/p_grenade.mdl
models/blackhawk/weapons/p_leg.mdl
models/blackhawk/weapons/p_uzi.mdl
models/blackhawk/weapons/v_9mmhandgun.mdl
models/blackhawk/weapons/v_fist.mdl
models/blackhawk/weapons/v_grenade.mdl
models/blackhawk/weapons/v_leg.mdl
models/blackhawk/weapons/v_uzi.mdl
models/blackhawk/weapons/w_9mmhandgun.mdl
models/blackhawk/weapons/w_fist.mdl
models/blackhawk/weapons/w_grenade.mdl
models/blackhawk/weapons/w_leg.mdl
models/blackhawk/weapons/w_uzi.mdl
sound/blackhawk/ambience/alarm.wav
sound/blackhawk/ambience/burning1.wav
sound/blackhawk/ambience/car_ambulance.wav
sound/blackhawk/ambience/city_sirenby.wav
sound/blackhawk/ambience/copter.wav
sound/blackhawk/ambience/haha.wav
sound/blackhawk/ambience/key.wav
sound/blackhawk/ambience/lv_fruit1.wav
sound/blackhawk/ambience/lv_fruit2.wav
sound/blackhawk/ambience/roam.wav
sound/blackhawk/ambience/scream.wav
sound/blackhawk/ambience/secret.wav
sound/blackhawk/ambience/teleport.wav
sound/blackhawk/ambience/teleport2.wav
sound/blackhawk/ambience/unlock.wav
sound/blackhawk/ghost/con_alert1.wav
sound/blackhawk/ghost/con_alert2.wav
sound/blackhawk/ghost/con_alert3.wav
sound/blackhawk/ghost/con_attack1.wav
sound/blackhawk/ghost/con_attack2.wav
sound/blackhawk/ghost/con_attack3.wav
sound/blackhawk/ghost/con_die1.wav
sound/blackhawk/ghost/con_die2.wav
sound/blackhawk/ghost/con_idle1.wav
sound/blackhawk/ghost/con_idle2.wav
sound/blackhawk/ghost/con_idle3.wav
sound/blackhawk/ghost/con_idle4.wav
sound/blackhawk/ghost/con_idle5.wav
sound/blackhawk/ghost/con_pain1.wav
sound/blackhawk/ghost/con_pain2.wav
sound/blackhawk/ghost/con_pain3.wav
sound/blackhawk/music/lateralus.wav
sound/blackhawk/music/schism.wav
sound/blackhawk/stalker/gr_die1.wav
sound/blackhawk/stalker/gr_die2.wav
sound/blackhawk/stalker/gr_die3.wav
sound/blackhawk/stalker/gr_pain1.wav
sound/blackhawk/stalker/gr_pain2.wav
sound/blackhawk/stalker/gr_pain3.wav
sound/blackhawk/stalker/gr_pain4.wav
sound/blackhawk/stalker/gr_pain5.wav
sound/blackhawk/zombie/zo_alert10.wav
sound/blackhawk/zombie/zo_alert20.wav
sound/blackhawk/zombie/zo_alert30.wav
sound/blackhawk/zombie/zo_attack1.wav
sound/blackhawk/zombie/zo_attack2.wav
sound/blackhawk/zombie/zo_death.wav
sound/blackhawk/zombie/zo_idle1.wav
sound/blackhawk/zombie/zo_idle2.wav
sound/blackhawk/zombie/zo_idle3.wav
sound/blackhawk/zombie/zo_idle4.wav
sound/blackhawk/zombie/zo_pain1.wav
sound/blackhawk/zombie/zo_pain2.wav
sound/weapons/clipin1.wav
sound/weapons/clipout1.wav
sound/weapons/sliderelease1.wav
