gfx/env/mountainpassBK.tga
gfx/env/mountainpassDN.tga
gfx/env/mountainpassFT.tga
gfx/env/mountainpassLF.tga
gfx/env/mountainpassRT.tga
gfx/env/mountainpassUP.tga
models/arc_fern.mdl
models/flo_bush.mdl
models/gibs_crate.mdl
models/gibs_stairsmetal.mdl
sound/central_bunker/birds_outside1.wav
sound/central_bunker/drboomsplash01.wav
sound/central_bunker/explo_metal01.wav