gfx/env/nstlgie_bk.tga
gfx/env/nstlgie_dn.tga
gfx/env/nstlgie_ft.tga
gfx/env/nstlgie_lf.tga
gfx/env/nstlgie_rt.tga
gfx/env/nstlgie_up.tga
lm_crossedpaths.wad
maps/crossedpaths3.cfg
models/adamr/ceiling_lamp_base.mdl
models/adamr/ceiling_lamp_bulb.mdl
models/cross_paths/antenne.mdl
models/cross_paths/crystal_cage.mdl
models/crystal_mission/banc.mdl
models/crystal_mission/box.mdl
models/crystal_mission/canape.mdl
models/crystal_mission/chaise_bureau.mdl
models/crystal_mission/chaise.mdl
models/crystal_mission/cookie_plat.mdl
models/crystal_mission/corbeille.mdl
models/crystal_mission/crystal.mdl
models/crystal_mission/ecran.mdl
models/crystal_mission/mug.mdl
models/crystal_mission/mug2.mdl
models/crystal_mission/note.mdl
models/crystal_mission/plante.mdl
models/crystal_mission/poubelle.mdl
models/crystal_mission/souris.mdl
models/crystal_mission/table_manger.mdl
models/crystal_mission/table.mdl
models/loulimi/barrier_tape.mdl
models/loulimi/bb_props.mdl
models/loulimi/big_cable.mdl
models/loulimi/big_spot_light.mdl
models/loulimi/cb_pipe.mdl
models/loulimi/gibs_plywood.mdl
models/loulimi/industrial_light.mdl
models/loulimi/lamp_red_base.mdl
models/loulimi/lamp_red_bulb.mdl
models/loulimi/lz_light.mdl
models/loulimi/outro_cp.mdl
models/loulimi/plastic_cup.mdl
models/loulimi/small_house.mdl
models/loulimi/small_pipe.mdl
models/loulimi/spot.mdl
models/loulimi/tripod.mdl
models/romrom/cptitle.mdl
sound/loulimi/bip0.ogg
sound/loulimi/bip1.ogg
sound/loulimi/bip2.ogg
sound/loulimi/coffee_filling.ogg
sound/loulimi/machine_ambient.ogg
sound/loulimi/plastic_cup.ogg
sound/marino/crossedpaths.wav
sound/marino/ohmamasaid.ogg
sprites/loulimi/mappingfusion.spr
sprites/loulimi/sn_hardhat.spr
sprites/loulimi/sn_hardhat1.spr