maps/cs_hokkaido.cfg
maps/cs_hokkaido.res
maps/cs_hokkaido_skl.cfg
gfx/env/g_nightbk.tga
gfx/env/g_nightdn.tga
gfx/env/g_nightft.tga
gfx/env/g_nightlf.tga
gfx/env/g_nightrt.tga
gfx/env/g_nightup.tga
models/csripent/knifer.mdl
models/csripent/knifer01.mdl
models/csripent/p_9mmar.mdl
models/csripent/p_9mmhandgun.mdl
models/csripent/p_crowbar.mdl
models/csripent/p_desert_eagle.mdl
models/csripent/p_grenade.mdl
models/csripent/p_m16.mdl
models/csripent/p_m40a1.mdl
models/csripent/p_saw.mdl
models/csripent/p_shotgun.mdl
models/csripent/p_uzi.mdl
models/csripent/p_uzi_gold.mdl
models/csripent/v_9mmar.mdl
models/csripent/v_9mmhandgun.mdl
models/csripent/v_crowbar.mdl
models/csripent/v_desert_eagle.mdl
models/csripent/v_grenade.mdl
models/csripent/v_m16a2.mdl
models/csripent/v_m40a1.mdl
models/csripent/v_medkit.mdl
models/csripent/v_saw.mdl
models/csripent/v_shotgun.mdl
models/csripent/v_uzi.mdl
models/csripent/w_9mmar.mdl
models/csripent/w_9mmhandgun.mdl
models/csripent/w_crowbar.mdl
models/csripent/w_crowbart.mdl
models/csripent/w_desert_eagle.mdl
models/csripent/w_grenade.mdl
models/csripent/w_m16.mdl
models/csripent/w_m40a1.mdl
models/csripent/w_saw.mdl
models/csripent/w_shotgun.mdl
models/csripent/w_uzi.mdl
models/csripent/weaponmodels.txt
sound/cs_hokkaido/bird2.wav
sound/cs_hokkaido/bird3.wav
sound/cs_hokkaido/bird.wav
sound/cs_hokkaido/cicada2.wav
sound/cs_hokkaido/cicada.wav
sound/cs_hokkaido/cricket.wav
sound/cs_hokkaido/gong.wav
sound/cs_hokkaido/hawk.wav
sound/cs_hokkaido/knifer.txt
sound/cs_hokkaido/music1.wav
sound/cs_hokkaido/nighting2.wav
sound/cs_hokkaido/nightingale.wav
sound/cs_hokkaido/owl1.wav
sound/cs_hokkaido/smallbird.wav
sound/csripent/knifer/attack.wav
sound/csripent/knifer/miss.wav
sound/csripent/scare.wav
sound/csripent/woo.wav
sound/weapons/CS/ak47_boltpull.wav
sound/weapons/CS/ak47_clipin.wav
sound/weapons/CS/ak47_clipout.wav
sound/weapons/CS/awp_clipin.wav
sound/weapons/CS/awp_clipout.wav
sound/weapons/CS/boltdown.wav
sound/weapons/CS/boltpull1.wav
sound/weapons/CS/boltup.wav
sound/weapons/CS/clipin1.wav
sound/weapons/CS/clipout1.wav
sound/weapons/CS/cliprelease1.wav
sound/weapons/CS/de_clipin.wav
sound/weapons/CS/de_clipout.wav
sound/weapons/CS/de_deploy.wav
sound/weapons/CS/famas_boltpull.wav
sound/weapons/CS/famas_boltslap.wav
sound/weapons/CS/famas_clipin.wav
sound/weapons/CS/famas_clipout.wav
sound/weapons/CS/famas_forearm.wav
sound/weapons/CS/fireinthehole.wav
sound/weapons/CS/knife_draw.wav
sound/weapons/CS/m249_boxin.wav
sound/weapons/CS/m249_boxout.wav
sound/weapons/CS/m249_chain.wav
sound/weapons/CS/m249_coverdown.wav
sound/weapons/CS/m249_coverup.wav
sound/weapons/CS/mac10_clipin.wav
sound/weapons/CS/mac10_clipout.wav
sound/weapons/CS/mac10_draw.wav
sound/weapons/CS/slideback1.wav
sound/weapons/CS/sliderelease1.wav
sprites/votemap/takesaba.spr