// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

ascii.wad
sound/dynamic_mapvote/dynamic_mapvote.ogg
sprites/dynamic_mapvote/halflife.spr
sprites/dynamic_mapvote/blue-shift.spr
sprites/dynamic_mapvote/opposing-force.spr
sprites/dynamic_mapvote/decay.spr
sprites/dynamic_mapvote/uplink.spr
sprites/dynamic_mapvote/afrikakorps.spr
sprites/dynamic_mapvote/auspices.spr
sprites/dynamic_mapvote/escape_series.spr
sprites/dynamic_mapvote/sandstone.spr
sprites/dynamic_mapvote/desertcircle.spr
sprites/dynamic_mapvote/quarter.spr
sprites/dynamic_mapvote/osprey.spr
sprites/dynamic_mapvote/intruder.spr
sprites/dynamic_mapvote/abandoned.spr
sprites/dynamic_mapvote/asmap.spr
sprites/dynamic_mapvote/fortified1.spr
sprites/dynamic_mapvote/crystal.spr
sprites/dynamic_mapvote/hplanet.spr
sprites/dynamic_mapvote/incoming.spr
sprites/dynamic_mapvote/infested.spr
sprites/dynamic_mapvote/mommamesa.spr
sprites/dynamic_mapvote/polar_rescue.spr
sprites/dynamic_mapvote/richard_boderman.spr
sprites/dynamic_mapvote/reco.spr
sprites/dynamic_mapvote/reo1.spr
sprites/dynamic_mapvote/richard_boderman.spr
sprites/dynamic_mapvote/sc_commandandconquer.spr
sprites/dynamic_mapvote/sc_another.spr
sprites/dynamic_mapvote/sc_persia.spr
sprites/dynamic_mapvote/snd.spr
sprites/dynamic_mapvote/suspension.spr
sprites/dynamic_mapvote/sc_royals.spr
sprites/dynamic_mapvote/th_escape.spr
sprites/dynamic_mapvote/svencooprpg.spr
sprites/dynamic_mapvote/svencoop1.spr
sprites/dynamic_mapvote/tf_original.spr
sprites/dynamic_mapvote/toonrun.spr
sprites/dynamic_mapvote/vger.spr
sprites/dynamic_mapvote/yabma.spr
sprites/dynamic_mapvote/theyhunger.spr
sprites/dynamic_mapvote/questionmark.spr
sprites/dynamic_mapvote/crimecity.spr
