// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/not_precached2.mdl
models/portal_house/race.mdl
models/scmod/phouse/race.mdl
models/scmod/phouse/weapons/highpowerblastershootred.mdl
models/scmod/phouse/weapons/p_768mmvulcan.mdl
models/scmod/phouse/weapons/p_plasmagun.mdl
models/scmod/phouse/weapons/v_768mmvulcan.mdl
models/scmod/phouse/weapons/v_plasmagun.mdl
models/scmod/phouse/weapons/w_768ammo.mdl
models/scmod/phouse/weapons/w_768mmvulcan.mdl
models/scmod/phouse/weapons/w_plasmaclip.mdl
models/scmod/phouse/weapons/w_plasmagun.mdl
sound/portal_house/weapons/p904_reload1.wav
sound/portal_house/weapons/plasma_re.wav
sound/scmod/phouse/race/race_alert1.ogg
sound/scmod/phouse/race/race_alert2.ogg
sound/scmod/phouse/race/race_die1.ogg
sound/scmod/phouse/race/race_die2.ogg
sound/scmod/phouse/race/race_idle2.ogg
sound/scmod/phouse/race/race_idle3.ogg
sound/scmod/phouse/race/race_idle4.ogg
sound/scmod/phouse/race/race_pain1.ogg
sound/scmod/phouse/race/race_pain2.ogg
sound/scmod/phouse/race/race_pain3.ogg
sound/scmod/phouse/race/race_pain4.ogg
sound/scmod/phouse/race/race_pain5.ogg
sound/scmod/phouse/weapons/fire_minigun01.ogg
sound/scmod/phouse/weapons/plasma2.ogg
sound/scmod/phouse/weapons/plasma_re.ogg
sound/weapons/ric_grass1.wav
sprites/scmod/phouse/640shl1.spr
sprites/scmod/phouse/640shl2.spr
sprites/scmod/phouse/640shl3.spr
sprites/scmod/phouse/640shl4.spr
sprites/scmod/phouse/blasterboltred.spr
sprites/scmod/phouse/blasterimpact.spr
sprites/scmod/phouse/cshoot.spr
sprites/scmod/phouse/expb1.spr
sprites/scmod/phouse/plasma.spr
sprites/scmod/phouse/weapon_dl44blaster.txt
sprites/scmod/phouse/weapon_e11blaster.txt
sprites/scmod/phouse/weapon_plasmagun.txt
sprites/scmod/phouse/weapon_t21blaster.txt
sprites/scmod/phouse/weapon_vulcan.txt
