// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

justzombies.wad
models/justzombies/monster/babyheadcrab_ghost.mdl
models/justzombies/monster/barney_enrico.mdl
models/justzombies/monster/bullsquid_ghost.mdl
models/justzombies/monster/bullsquid_tree.mdl
models/justzombies/monster/controller_ghost.mdl
models/justzombies/monster/ghost_count.mdl
models/justzombies/monster/ghost_hellmother.mdl
models/justzombies/monster/ghost_jeep.mdl
models/justzombies/monster/ghost_nature.mdl
models/justzombies/monster/ghost_poltergeist.mdl
models/justzombies/monster/ghost_thelie.mdl
models/justzombies/monster/gonome_ghost.mdl
models/justzombies/monster/gonome_paranoia.mdl
models/justzombies/monster/headcrab_prop.mdl
models/justzombies/monster/houndeye_prop.mdl
models/justzombies/monster/islave_painting.mdl
models/justzombies/monster/pitdrone_ghost.mdl
models/justzombies/monster/strooper_ghost.mdl
models/justzombies/monster/zombie.mdl
models/justzombies/monster/zombie_crimsonhead.mdl
models/justzombies/monster/zombie_drzombie.mdl
models/justzombies/monster/zombie_drzombie01.mdl
models/justzombies/monster/zombie_drzombie02.mdl
models/justzombies/monster/zombie_drzombiet.mdl
models/justzombies/monster/zombie_paranoia.mdl
models/justzombies/props/bed2.mdl
models/justzombies/props/bigbed.mdl
models/JustZombies/props/bonegibs.mdl
models/justzombies/props/bulb.mdl
models/justzombies/props/bulb_bright.mdl
models/justzombies/props/by_boat.mdl
models/justzombies/props/chandbig_bright.mdl
models/justzombies/props/chandbig_bw_bright.mdl
models/justzombies/props/couch3.mdl
models/justzombies/props/crow.mdl
models/justzombies/props/grandfather_clock.mdl
models/justzombies/props/jameson.mdl
models/justzombies/props/jeep02.mdl
models/justzombies/props/key_silver.mdl
models/justzombies/props/lip_cabinet_dark.mdl
models/justzombies/props/lip_dresser.mdl
models/justzombies/props/lock.mdl
models/justzombies/props/mesa3.mdl
models/justzombies/props/plate.mdl
models/justzombies/props/seat1.mdl
models/justzombies/props/sitsci.mdl
models/justzombies/props/skeleton.mdl
models/justzombies/props/sp_parasha.mdl
models/justzombies/props/statue_deserto.mdl
models/justzombies/props/statue_rpd_grey.mdl
models/justzombies/props/tub.mdl
models/justzombies/props/walllamp.mdl
models/justzombies/props/washbowl.mdl
models/justzombies/props/wooden_chair.mdl
models/justzombies/props/xen_plant1.mdl
models/justzombies/props/xen_plant3.mdl
models/justzombies/props/xen_plant6.mdl
models/justzombies/props/xen_tree6_3.mdl
models/justzombies/props/xen_tree6_3bw.mdl
models/justzombies/props/xen_vase1.mdl
models/justzombies/props/zp_sink.mdl
models/justzombies/weapons/p_ghostbasher.mdl
models/justzombies/weapons/p_ghostegon.mdl
models/justzombies/weapons/p_ghostgauss.mdl
models/justzombies/weapons/p_spaten.mdl
models/justzombies/weapons/v_ghostbasher.mdl
models/justzombies/weapons/v_ghostegon.mdl
models/justzombies/weapons/v_ghostgauss.mdl
models/JustZombies/weapons/v_spaten.mdl
models/justzombies/weapons/w_ghostbasher.mdl
models/justzombies/weapons/w_ghostegon.mdl
models/justzombies/weapons/w_ghostgauss.mdl
models/JustZombies/weapons/w_spaten.mdl
sound/JustMansion/fx_clock.wav
sound/JustMansion/fx_creepywind.wav
sound/JustMansion/fx_man_death.wav
sound/JustMansion/fx_random01.wav
sound/JustMansion/fx_random02.wav
sound/JustMansion/fx_random03.wav
sound/JustMansion/fx_random04.wav
sound/JustMansion/fx_random05.wav
sound/justzombies/intro_mansion.mp3
sound/justzombies/zombie/alert.wav
sound/justzombies/zombie/alert2.wav
sound/justzombies/zombie/alert3.wav
sound/justzombies/zombie/attack.wav
sound/justzombies/zombie/attack2.wav
sound/justzombies/zombie/attack3.wav
sound/justzombies/zombie/attack4.wav
sound/justzombies/zombie/attack5.wav
sound/justzombies/zombie/idle1.wav
sound/justzombies/zombie/idle2.wav
sound/justzombies/zombie/idle3.wav
sound/justzombies/zombie/idle4.wav
sound/justzombies/zombie/miss.wav
sound/justzombies/zombie/miss2.wav
sound/justzombies/zombie/pain1.wav
sound/justzombies/zombie/pain2.wav
sound/weapons/629_shells_land.wav
sound/weapons/revolvers_bulletsin.wav
sound/weapons/revolvers_rod.wav
sound/weapons/revolvers_wheelin.wav
sound/weapons/revolvers_wheelout.wav
sprites/justzombies/vortimorph.spr
sprites/justzombies/weapon_ghostegon.txt
