// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

justzombies.wad
models/justzombies/monster/apache_hovercopter.mdl
models/justzombies/monster/barney_engineer.mdl
models/justzombies/monster/hgrunt_specops.mdl
models/justzombies/monster/hwgrunt_loader.mdl
models/justzombies/monster/hwgrunt_space.mdl
models/justzombies/props/bs_experiment.mdl
models/justzombies/props/coffee.mdl
models/justzombies/props/couch.mdl
models/justzombies/props/deadsoldier.mdl
models/justzombies/props/e4g1e_merc.mdl
models/justzombies/props/headless_zombie.mdl
models/justzombies/props/seat.mdl
models/justzombies/props/vend3.mdl
models/justzombies/props/vend6.mdl
models/justzombies/props/viper_gordon.mdl
models/justzombies/props/water.mdl
models/JustZombies/weapons/p_bigboot.mdl
models/justzombies/weapons/p_ghostegon.mdl
models/JustZombies/weapons/p_nothing.mdl
models/justzombies/weapons/p_xenmedkit.mdl
models/JustZombies/weapons/v_bigboot.mdl
models/justzombies/weapons/v_ghostegon.mdl
models/justzombies/weapons/v_spore_launcher.mdl
models/JustZombies/weapons/v_xenbeam.mdl
models/justzombies/weapons/v_xencharge.mdl
models/JustZombies/weapons/v_xenclaws.mdl
models/justzombies/weapons/v_xenmedkit.mdl
models/JustZombies/weapons/w_bigboot.mdl
models/JustZombies/weapons/w_nothing.mdl
models/justzombies/weapons/w_xenmedkit.mdl
models/player/justislave/justislave.bmp
models/player/justislave/justislave.mdl
sound/justislave/alien_humongo.wav
sound/justislave/pl_claw_strike1.wav
sound/justislave/pl_claw_strike2.wav
sound/justislave/pl_claw_strike3.wav
sound/justislave/pl_clawmiss1.wav
sound/justislave/pl_fire1.wav
sound/justislave/pl_jump1.wav
sound/justislave/pl_jump2.wav
sound/justislave/pl_jumpland2.wav
sound/justislave/pl_ladder1.wav
sound/justislave/pl_ladder2.wav
sound/justislave/pl_ladder3.wav
sound/justislave/pl_ladder4.wav
sound/justzombies/music_car.mp3
