// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/fullmoonbk.tga
gfx/env/fullmoondn.tga
gfx/env/fullmoonft.tga
gfx/env/fullmoonlf.tga
gfx/env/fullmoonrt.tga
gfx/env/fullmoonup.tga
justzombies.wad
models/justzombies/monster/agrunt_armored.mdl
models/justzombies/monster/barnabus_hybrid.mdl
models/justzombies/monster/barnabus_shield.mdl
models/justzombies/monster/barney_maimed.mdl
models/justzombies/monster/gonome_melissa.mdl
models/justzombies/monster/gonome_oswald.mdl
models/justzombies/monster/gonome_tyrant.mdl
models/justzombies/monster/headcrab_bunny.mdl
models/justzombies/monster/hgrunt_klaus.mdl
models/justzombies/monster/islave_docslave.mdl
models/justzombies/monster/zombie.mdl
models/justzombies/monster/zombie_barnabus.mdl
models/justzombies/monster/zombie_docslave.mdl
models/justzombies/monster/zombie_parasite.mdl
models/justzombies/props/barnacle.mdl
models/justzombies/props/barney_hand.mdl
models/justzombies/props/barnvictim.mdl
models/justzombies/props/blood.mdl
models/justzombies/props/bonepile.mdl
models/justzombies/props/bulb.mdl
models/justzombies/props/butch.mdl
models/justzombies/props/coffee.mdl
models/justzombies/props/couch.mdl
models/JustZombies/props/deadgrunt.mdl
models/justzombies/props/deadzombiesci.mdl
models/justzombies/props/gibman.mdl
models/justzombies/props/islave0.mdl
models/justzombies/props/islave100.mdl
models/justzombies/props/islave25_1.mdl
models/justzombies/props/islave33.mdl
models/justzombies/props/islave45.mdl
models/justzombies/props/islave75.mdl
models/justzombies/props/jeep02.mdl
models/justzombies/props/lab_corpses.mdl
models/justzombies/props/radio.mdl
models/justzombies/props/seat.mdl
models/justzombies/props/vend3.mdl
models/justzombies/props/vend6.mdl
models/justzombies/props/water.mdl
models/justzombies/props/zombie_sitting.mdl
models/JustZombies/weapons/p_bigboot.mdl
models/JustZombies/weapons/v_bigboot.mdl
models/JustZombies/weapons/w_bigboot.mdl
sound/JustZombies/fx_hit.wav
sound/JustZombies/fx_hybridtalk.wav
sound/justzombies/intro_zombies.mp3
sound/justzombies/music_radio.mp3
