// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/nmislandbk.tga
gfx/env/nmislanddn.tga
gfx/env/nmislandft.tga
gfx/env/nmislandlf.tga
gfx/env/nmislandrt.tga
gfx/env/nmislandup.tga
models/nm_darkisland/nm_cz_plant1.mdl
models/nm_darkisland/nm_cz_plant2.mdl
models/nm_darkisland/nm_cz_plant5.mdl
models/nm_darkisland/nm_cz_plant6.mdl
models/nm_darkisland/nm_cz_plant6big.mdl
models/nm_darkisland/nm_cz_plant7.mdl
models/nm_darkisland/nm_cz_treetop1.mdl
models/nm_darkisland/nm_cz_treetop2.mdl
models/nm_darkisland/nm_cz_treetop3.mdl
models/nm_darkisland/nm_dryad.mdl
models/nm_darkisland/nm_gand.mdl
models/nm_darkisland/nm_gandt.mdl
models/nm_darkisland/nm_gargcustom.mdl
models/nm_darkisland/nm_gargcustomt.mdl
models/nm_darkisland/nm_magic.mdl
models/nm_darkisland/nm_tallgrass.mdl
models/nm_darkisland/nm_vines.mdl
models/nm_darkisland/p_nm_staff.mdl
models/nm_darkisland/p_nmbone.mdl
models/nm_darkisland/p_nmpickaxe.mdl
models/nm_darkisland/palmtree.mdl
models/nm_darkisland/pi_fern.mdl
models/nm_darkisland/v_nm_staff.mdl
models/nm_darkisland/v_nmbone.mdl
models/nm_darkisland/v_nmpickaxe.mdl
models/nm_darkisland/w_nm_staff.mdl
models/nm_darkisland/w_nmbone.mdl
models/nm_darkisland/w_nmbonet.mdl
models/nm_darkisland/w_nmpickaxe.mdl
sound/nm_darkisland/df_amb3.wav
sound/nm_darkisland/duh_tree.wav
sound/nm_darkisland/nm_evanescence_lies.wav
sound/nm_darkisland/nm_jsfx1.wav
sound/nm_darkisland/nm_jsfx2.wav
sound/nm_darkisland/nm_jsfx3.wav
sound/nm_darkisland/nm_jsfx4.wav
sound/nm_darkisland/nm_jsfx5.wav
sound/nm_darkisland/nm_jsfx6.wav
sound/nm_darkisland/nm_jsfx7.wav
sound/nm_darkisland/nm_jsfx8.wav
sound/nm_darkisland/nm_jsfx_a1.wav
sound/nm_darkisland/nm_jsfx_a2.wav
sound/nm_darkisland/nm_jsfx_a3.wav
sound/nm_darkisland/nm_waterfall.wav
sound/nm_darkisland/waterrun.wav
sprites/nm_darkisland/smokepuff.spr
