// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

events/muzzle_ns_gg.txt
events/muzzle_ns_hmg.txt
events/muzzle_ns_mg.txt
events/muzzle_ns_pistol.txt
events/muzzle_ns_sg.txt
gfx/env/metro_nitebk.tga
gfx/env/metro_nitedn.tga
gfx/env/metro_niteft.tga
gfx/env/metro_nitelf.tga
gfx/env/metro_nitert.tga
gfx/env/metro_niteup.tga
gfx/env/space_01bk.tga
gfx/env/space_01dn.tga
gfx/env/space_01ft.tga
gfx/env/space_01lf.tga
gfx/env/space_01rt.tga
gfx/env/space_01up.tga
models/chan_space_escape/cc_couch_01.mdl
models/chan_space_escape/snowmount.mdl
models/chan_space_escape/earth.mdl
models/chan_space_escape/items/new_arm_lab.mdl
models/chan_space_escape/items/new_battery.mdl
models/chan_space_escape/items/new_cc.mdl
models/chan_space_escape/items/new_info.mdl
models/chan_space_escape/items/new_k_card.mdl
models/chan_space_escape/items/new_obs.mdl
models/chan_space_escape/items/new_phase.mdl
models/chan_space_escape/items/new_proto.mdl
models/chan_space_escape/items/new_res.mdl
models/chan_space_escape/items/new_toolbox.mdl
models/chan_space_escape/items/new_turret.mdl
models/chan_space_escape/items/w_ammo.mdl
models/chan_space_escape/items/w_health.mdl
models/chan_space_escape/items/w_heavy.mdl
models/chan_space_escape/speaker2.mdl
models/chan_space_escape/table.mdl
models/ns/grenade.mdl
models/ns/monsters/b_sentry_test_a.mdl
models/ns/monsters/ba_offense_test_a.mdl
models/ns/monsters/fade_test_b.mdl
models/ns/monsters/gorge_test_a.mdl
models/ns/monsters/onos_test_a.mdl
models/ns/monsters/skulk_test_b.mdl
models/ns/monsters/stomp_test_a.mdl
models/ns/p_gg.mdl
models/ns/p_gr.mdl
models/ns/p_hg.mdl
models/ns/p_hmg.mdl
models/ns/p_kn.mdl
models/ns/p_mg.mdl
models/ns/p_mine.mdl
models/ns/p_sentrygun_ns.mdl
models/ns/p_sg.mdl
models/ns/shell.mdl
models/ns/shotshell.mdl
models/ns/spike.mdl
models/ns/v_gg.mdl
models/ns/v_gr.mdl
models/ns/v_hg.mdl
models/ns/v_hmg.mdl
models/ns/v_kn.mdl
models/ns/v_mg.mdl
models/ns/v_mine.mdl
models/ns/v_medkit.mdl
models/ns/v_sentrygun_ns.mdl
models/ns/v_sg.mdl
models/ns/w_gg.mdl
models/ns/w_gr.mdl
models/ns/w_hg.mdl
models/ns/w_hmg.mdl
models/ns/w_kn.mdl
models/ns/w_mg.mdl
models/ns/w_mine.mdl
models/ns/w_mine2.mdl
models/ns/w_sentrygun_ns.mdl
models/ns/w_sg.mdl
models/player/ns_heavy/ns_heavy.mdl
sound/chan_space/ambience/alarmloop.wav
sound/chan_space/ambience/atmospheric.mp3
sound/chan_space/ambience/b2.mp3
sound/chan_space/ambience/b3.wav
sound/chan_space/ambience/b5.wav
sound/chan_space/ambience/bastturbine.wav
sound/chan_space/ambience/bastwind2.wav
sound/chan_space/ambience/bf.wav
sound/chan_space/ambience/bg.wav
sound/chan_space/ambience/controlroom.mp3
sound/chan_space/ambience/echodrops.mp3
sound/chan_space/ambience/emdrill.wav
sound/chan_space/ambience/eng.wav
sound/chan_space/ambience/engagelev.wav
sound/chan_space/ambience/enginethrob.mp3
sound/chan_space/ambience/hive_ambient.wav
sound/chan_space/ambience/klaxon.wav
sound/chan_space/ambience/klaxon2.wav
sound/chan_space/ambience/klaxon4.wav
sound/chan_space/ambience/lkburner2.wav
sound/chan_space/ambience/lkburner3.wav
sound/chan_space/ambience/lowsteam.wav
sound/chan_space/ambience/metalstress.wav
sound/chan_space/ambience/processing.wav
sound/chan_space/ambience/pulsingwhine.wav
sound/chan_space/ambience/rumblewhine.wav
sound/chan_space/ambience/shaft.wav
sound/chan_space/ambience/steamburst4.wav
sound/chan_space/buttons/button5.wav
sound/chan_space/buttons/button7.wav
sound/chan_space/buttons/button9.wav
sound/chan_space/countdown.wav
sound/chan_space/doors/doormove2.wav
sound/chan_space/doors/doormove3.wav
sound/chan_space/doors/doormove4.wav
sound/chan_space/doors/doormove5.wav
sound/chan_space/doors/doormove7.wav
sound/chan_space/doors/doormove8.wav
sound/chan_space/doors/doorstop1.wav
sound/chan_space/doors/doorstop2.wav
sound/chan_space/doors/doorstop3.wav
sound/chan_space/doors/doorstop4.wav
sound/chan_space/explodingship.wav
sound/chan_space/gamestart1.wav
sound/chan_space/goodend.wav
sound/chan_space/main_loop.wav
sound/chan_space/misc/b_marine_deploy.wav
sound/chan_space/misc/ship_jets.wav
sound/chan_space/p_loop.wav
sound/chan_space/s_loop.wav
sound/chan_space/tock.mp3
sound/chan_space/tock.mp3
sound/chan_space/medic.wav
sound/chan_space/ammo.wav
sound/ns/monsters/asay31.wav
sound/ns/monsters/b_sentry/turret-1.wav
sound/ns/monsters/b_sentry/turret-2.wav
sound/ns/monsters/b_sentry/turret-3.wav
sound/ns/monsters/b_sentry/turret-4.wav
sound/ns/monsters/b_sentry/turret_deploy.wav
sound/ns/monsters/b_sentry/turret_ping.wav
sound/ns/monsters/ba_offense/alien_chamber_deploy.wav
sound/ns/monsters/ba_offense/alien_chamber_die.wav
sound/ns/monsters/ba_offense/aturret-1.wav
sound/ns/monsters/fade/blinksuccess.wav
sound/ns/monsters/fade/claws1.wav
sound/ns/monsters/fade/claws2.wav
sound/ns/monsters/fade/claws3.wav
sound/ns/monsters/fade/role6_die1.wav
sound/ns/monsters/fade/role6_idle1.wav
sound/ns/monsters/fade/role6_move1.wav
sound/ns/monsters/fade/role6_pain1.wav
sound/ns/monsters/fade/role6_wound1.wav
sound/ns/monsters/gorge/alien_spray.wav
sound/ns/monsters/gorge/role3_die1.wav
sound/ns/monsters/gorge/role3_idle1.wav
sound/ns/monsters/gorge/role3_pain1.wav
sound/ns/monsters/gorge/role3_spawn1.wav
sound/ns/monsters/gorge/role3_spawn2.wav
sound/ns/monsters/gorge/role3_wound1.wav
sound/ns/monsters/gorge/spit-1.wav
sound/ns/monsters/gorge/spit-2.wav
sound/ns/monsters/onos/role7_die1.wav
sound/ns/monsters/onos/role7_die2.wav
sound/ns/monsters/onos/role7_idle1.wav
sound/ns/monsters/onos/role7_pain1.wav
sound/ns/monsters/onos/role7_spawn1.wav
sound/ns/monsters/onos/role7_wound1.wav
sound/ns/monsters/onos/step1.wav
sound/ns/monsters/onos/step2.wav
sound/ns/monsters/onos/step3.wav
sound/ns/monsters/onos/stomp.wav
sound/ns/monsters/onos/swipe1.wav
sound/ns/monsters/onos/swipe2.wav
sound/ns/monsters/onos/swipe3.wav
sound/ns/monsters/onos/swipe4.wav
sound/ns/monsters/skulk/bite.wav
sound/ns/monsters/skulk/bite2.wav
sound/ns/monsters/skulk/leap1.wav
sound/ns/monsters/skulk/leaphit1.wav
sound/ns/monsters/skulk/role4_die1.wav
sound/ns/monsters/skulk/role4_idle1.wav
sound/ns/monsters/skulk/role4_pain1.wav
sound/ns/monsters/skulk/role4_wound1.wav
sound/ns/monsters/skulk/role4_wound2.wav
sound/ns/monsters/skulk/role5_move1.wav
sound/ns/monsters/skulk/step1.wav
sound/ns/monsters/skulk/step2.wav
sound/ns/monsters/skulk/step4.wav
sound/ns/weapons/explode3.wav
sound/ns/weapons/explode4.wav
sound/ns/weapons/explode5.wav
sound/ns/weapons/gg/gg-1.wav
sound/ns/weapons/gg/gg_draw.wav
sound/ns/weapons/gg/gg_insert.wav
sound/ns/weapons/gg/gg_reload_end.wav
sound/ns/weapons/gg/gg_reload_start.wav
sound/ns/weapons/gg/gg_rotate.wav
sound/ns/weapons/gr/grenade_draw.wav
sound/ns/weapons/gr/grenade_hit1.wav
sound/ns/weapons/gr/grenade_hit2.wav
sound/ns/weapons/gr/grenade_hit3.wav
sound/ns/weapons/gr/grenade_prime.wav
sound/ns/weapons/gr/grenade_throw.wav
sound/ns/weapons/hg/hg-1.wav
sound/ns/weapons/hg/pistol_clipin.wav
sound/ns/weapons/hg/pistol_clipout.wav
sound/ns/weapons/hg/pistol_draw.wav
sound/ns/weapons/hg/pistol_slide_release.wav
sound/ns/weapons/hmg/hmg-1.wav
sound/ns/weapons/hmg/hmg_clipin.wav
sound/ns/weapons/hmg/hmg_clipout.wav
sound/ns/weapons/hmg/hmg_close.wav
sound/ns/weapons/hmg/hmg_draw.wav
sound/ns/weapons/hmg/hmg_open.wav
sound/ns/weapons/hmg/hmg_slide.wav
sound/ns/weapons/kn/kn-1.wav
sound/ns/weapons/kn/kn-2.wav
sound/ns/weapons/kn/kn-deploy.wav
sound/ns/weapons/kn/kn-hit-1.wav
sound/ns/weapons/kn/kn-hit-2.wav
sound/ns/weapons/kn/kn-hit-wall.wav
sound/ns/weapons/mg/lmg_clipin.wav
sound/ns/weapons/mg/lmg_clipout.wav
sound/ns/weapons/mg/lmg_draw.wav
sound/ns/weapons/mg/mg-1.wav
sound/ns/weapons/mine/mine_activate.wav
sound/ns/weapons/mine/mine_charge.wav
sound/ns/weapons/mine/mine_deploy.wav
sound/ns/weapons/mine/mine_draw.wav
sound/ns/weapons/mine/mine_step.wav
sound/ns/weapons/sg/sg-1.wav
sound/ns/weapons/sg/sg-cock.wav
sound/ns/weapons/sg/shotgun_draw.wav
sound/ns/weapons/sg/shotgun_pump.wav
sound/ns/weapons/sg/shotgun_reload.wav
sound/ns/weapons/sg/shotgun_stock_release.wav
sprites/chan_space/ayumiglow2.spr
sprites/chan_space/ballsmoke.spr
sprites/chan_space/blueflare2.spr
sprites/chan_space/flare3metal.spr
sprites/chan_space/haze.spr
sprites/chan_space/items/b1.spr
sprites/chan_space/items/b2.spr
sprites/chan_space/items/b3.spr
sprites/chan_space/items/b4.spr
sprites/chan_space/items/b5.spr
sprites/chan_space/items/b6.spr
sprites/chan_space/items/b7.spr
sprites/chan_space/items/b8.spr
sprites/chan_space/items/batrv2.spr
sprites/chan_space/items/batv2.spr
sprites/chan_space/items/heavy.spr
sprites/chan_space/items/k1.spr
sprites/chan_space/items/k10.spr
sprites/chan_space/items/k11.spr
sprites/chan_space/items/k12.spr
sprites/chan_space/items/k13.spr
sprites/chan_space/items/k14.spr
sprites/chan_space/items/k15.spr
sprites/chan_space/items/k16.spr
sprites/chan_space/items/k2.spr
sprites/chan_space/items/k3.spr
sprites/chan_space/items/k4.spr
sprites/chan_space/items/k5.spr
sprites/chan_space/items/k6.spr
sprites/chan_space/items/k7.spr
sprites/chan_space/items/k8.spr
sprites/chan_space/items/k9.spr
sprites/chan_space/items/n1.spr
sprites/chan_space/items/n10.spr
sprites/chan_space/items/n11.spr
sprites/chan_space/items/n12.spr
sprites/chan_space/items/n13.spr
sprites/chan_space/items/n14.spr
sprites/chan_space/items/n15.spr
sprites/chan_space/items/n16.spr
sprites/chan_space/items/n2.spr
sprites/chan_space/items/n3.spr
sprites/chan_space/items/n4.spr
sprites/chan_space/items/n5.spr
sprites/chan_space/items/n6.spr
sprites/chan_space/items/n7.spr
sprites/chan_space/items/n8.spr
sprites/chan_space/items/n9.spr
sprites/chan_space/items/tool.spr
sprites/chan_space/lobby/goal2.spr
sprites/chan_space/lobby/lobbyhelp.spr
sprites/chan_space/lobby/lobbyhelp2.spr
sprites/chan_space/lobby/lobby_3.spr
sprites/chan_space/lobby/lobby_4.spr
sprites/chan_space/lobby/logo_w1.spr
sprites/chan_space/lobby/logo_w2.spr
sprites/chan_space/lobby/logo_w3.spr
sprites/chan_space/lobby/sign_w1.spr
sprites/chan_space/lobby/sign_w2.spr
sprites/chan_space/lobby/sign_w3.spr
sprites/chan_space/moths.spr
sprites/chan_space/orflare3.spr
sprites/chan_space/redflare2.spr
sprites/chan_space/rjet1.spr
sprites/chan_space/wdrip2.spr
sprites/chan_space/xsmoke1.spr
sprites/ns/640hud7.spr
sprites/ns/640mw1-s.spr
sprites/ns/640mw1.spr
sprites/ns/640mw2-s.spr
sprites/ns/640mw2.spr
sprites/ns/bacteria.spr
sprites/ns/bigspit.spr
sprites/ns/chamberdeath.spr
sprites/ns/muzzleflash1.spr
sprites/ns/stomp.spr
sprites/ns/weapon_ns_grenade.txt
sprites/ns/weapon_ns_grenadegun.txt
sprites/ns/weapon_ns_heavymachinegun.txt
sprites/ns/weapon_ns_knife.txt
sprites/ns/weapon_ns_machinegun.txt
sprites/ns/weapon_ns_mine.txt
sprites/ns/weapon_ns_pistol.txt
sprites/ns/weapon_ns_shotgun.txt
sprites/ns/xhairgl140.spr
sprites/ns/xhairmw1.spr
sprites/ns/xhairmw5.spr
sprites/sentry/weapon_sentry.spr
sprites/sentry/weapon_sentry.txt
