// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

3dmsnowy.wad
barbarossa.wad
barbarossa2.wad
barbarossa_imp.wad
barbarossa_imp2.wad
barbarossa_imp3.wad
hwnc_blackbush_b1.wad
maps/operation_barbarossa.bsp
models/barbarossa/beachcitizen1.mdl
models/barbarossa/beachcitizen2.mdl
models/barbarossa/beachcitizen4.mdl
models/barbarossa/bm21.mdl
models/barbarossa/burgdorf.mdl
models/barbarossa/bush_japan_fern_01.mdl
models/barbarossa/coffeemachine.mdl
models/barbarossa/cybertruck.mdl
models/barbarossa/fireplace.mdl
models/barbarossa/forklift.mdl
models/barbarossa/goebbels.mdl
models/barbarossa/hitler.mdl
models/barbarossa/hitler3.mdl
models/barbarossa/hitlerwife.mdl
models/barbarossa/jodl.mdl
models/barbarossa/keitel.mdl
models/barbarossa/krebs.mdl
models/barbarossa/lenin.mdl
models/barbarossa/limo.mdl
models/barbarossa/m1a1.mdl
models/barbarossa/mon_estrutura.mdl
models/barbarossa/mon_fakew.mdl
models/barbarossa/mon_farol.mdl
models/barbarossa/mon_ponte.mdl
models/barbarossa/mon_veg1.mdl
models/barbarossa/mon_veg2.mdl
models/barbarossa/mon_veg3.mdl
models/barbarossa/nazi5.mdl
models/barbarossa/nazi6.mdl
models/barbarossa/snackmachine_large.mdl
models/barbarossa/snackmachine_small.mdl
models/barbarossa/various/binocular.mdl
models/barbarossa/various/bomb.mdl
models/barbarossa/various/coffeemug.mdl
models/barbarossa/various/extinguisher.mdl
models/barbarossa/various/Gas_Bottle_Cart.mdl
models/barbarossa/various/hatchet.mdl
models/barbarossa/various/Ladder.mdl
models/barbarossa/various/modelship.mdl
models/barbarossa/various/Oil_Bottle.mdl
models/barbarossa/various/portablegenerator.mdl
models/barbarossa/various/redladder.mdl
models/barbarossa/various/rifle_case.mdl
models/barbarossa/various/roadblock.mdl
models/barbarossa/various/teddybear.mdl
models/barbarossa/various/tree_pine_evergreen.mdl
models/barbarossa/wreck_firetruck.mdl
models/barbarossa/wreck_fuel_truck.mdl
models/barbarossa/wreck_m1a1.mdl
models/barbarossa/Xen_barrel3_1.mdl
models/barbarossa/Xen_barrel4_2.mdl
models/barbarossa/Xen_bush_big.mdl
models/barbarossa/Xen_tree4.mdl
models/barbarossa/Xen_tree4_3.mdl
models/barbarossa/Xen_tree6.mdl
models/barbarossa/Xen_tree6_3.mdl
models/pallet_with_bags.mdl
models/pallet_with_bags2.mdl
models/support1.mdl
models/support2.mdl
models/support3.mdl
models/ww2projekt/c96/p_c96.mdl
models/ww2projekt/c96/v_c96.mdl
models/ww2projekt/c96/w_c96.mdl
models/ww2projekt/dp28/p_dp28bd.mdl
models/ww2projekt/dp28/p_dp28bu.mdl
models/ww2projekt/dp28/v_dp28.mdl
models/ww2projekt/dp28/w_dp28.mdl
models/ww2projekt/fg42/p_fg42s.mdl
models/ww2projekt/fg42/p_fg42sbd.mdl
models/ww2projekt/fg42/v_dscopedfg42.mdl
models/ww2projekt/fg42/w_fg42s.mdl
models/ww2projekt/g43/p_k43.mdl
models/ww2projekt/g43/v_k43PHX.mdl
models/ww2projekt/g43/w_k43.mdl
models/ww2projekt/kar98k/p_k98.mdl
models/ww2projekt/kar98k/v_98k.mdl
models/ww2projekt/kar98k/w_98k.mdl
models/ww2projekt/luger/p_lugerp08.mdl
models/ww2projekt/luger/v_lugerp08.mdl
models/ww2projekt/luger/w_lugerp08.mdl
models/ww2projekt/m1885/p_nagm1885.mdl
models/ww2projekt/m1885/v_nagm1885.mdl
models/ww2projekt/m1885/w_nagm1885.mdl
models/ww2projekt/maxim/p_maxim.mdl
models/ww2projekt/maxim/v_maxim.mdl
models/ww2projekt/maxim/w_maxim.mdl
models/ww2projekt/mg34/p_mg34bd.mdl
models/ww2projekt/mg34/v_mg34.mdl
models/ww2projekt/mg34/w_mg34.mdl
models/ww2projekt/mg42/p_mg42bd.mdl
models/ww2projekt/mg42/p_mg42bu.mdl
models/ww2projekt/mg42/v_mg42.mdl
models/ww2projekt/mg42/w_mg42.mdl
models/ww2projekt/mp40/p_mp40.mdl
models/ww2projekt/mp40/v_mp40.mdl
models/ww2projekt/mp40/w_mp40.mdl
models/ww2projekt/mp44/p_stg44.mdl
models/ww2projekt/mp44/v_mp44BETA.mdl
models/ww2projekt/mp44/w_mp44.mdl
models/ww2projekt/nagant/p_nagant.mdl
models/ww2projekt/nagant/v_nagant.mdl
models/ww2projekt/nagant/w_nagant.mdl
models/ww2projekt/nagantscoped/p_nagantscoped.mdl
models/ww2projekt/nagantscoped/v_nagantscoped.mdl
models/ww2projekt/nagantscoped/w_nagantscoped.mdl
models/ww2projekt/panzerfaust/p_panzerfaust.mdl
models/ww2projekt/panzerfaust/v_panzerfaust.mdl
models/ww2projekt/panzerfaust/w_panzerfaust.mdl
models/ww2projekt/panzerfaust/w_panzerfaust_empty.mdl
models/ww2projekt/panzerfaust/w_panzerfaust_rocket.mdl
models/ww2projekt/panzerschreck/p_pschreck.mdl
models/ww2projekt/panzerschreck/v_panzerschreck.mdl
models/ww2projekt/panzerschreck/w_pschreck.mdl
models/ww2projekt/panzerschreck/w_pschreck_rocket.mdl
models/ww2projekt/ppsh41/p_ppsh.mdl
models/ww2projekt/ppsh41/v_ppsh.mdl
models/ww2projekt/ppsh41/w_ppsh.mdl
models/ww2projekt/rgdgren/p_rgdgren.mdl
models/ww2projekt/rgdgren/v_rgdgren.mdl
models/ww2projekt/rgdgren/w_rgdgren.mdl
models/ww2projekt/scoped98k/p_k98s.mdl
models/ww2projekt/scoped98k/v_scoped98kBETA.mdl
models/ww2projekt/scoped98k/w_scoped98k.mdl
models/ww2projekt/shell_large.mdl
models/ww2projekt/shell_medium.mdl
models/ww2projekt/shell_small.mdl
models/ww2projekt/spade/p_spade.mdl
models/ww2projekt/spade/v_spade.mdl
models/ww2projekt/spade/w_spade.mdl
models/ww2projekt/stick/p_stick.mdl
models/ww2projekt/stick/v_stick.mdl
models/ww2projekt/stick/w_stick.mdl
models/ww2projekt/svt40/p_svt40.mdl
models/ww2projekt/svt40/v_svt40.mdl
models/ww2projekt/svt40/w_svt40.mdl
models/ww2projekt/tokarev/p_tokarev.mdl
models/ww2projekt/tokarev/v_tokarev.mdl
models/ww2projekt/tokarev/w_tokarev.mdl
sound/barbarossa/angel.mp3
sound/barbarossa/beachambient.ogg
sound/barbarossa/chimes.wav
sound/barbarossa/cicada3.wav
sound/barbarossa/crow.wav
sound/barbarossa/deutschland.mp3
sound/barbarossa/erika.mp3
sound/barbarossa/explosion.mp3
sound/barbarossa/fire.ogg
sound/barbarossa/flmgrexp.wav
sound/barbarossa/kolizey.mp3
sound/barbarossa/leakinggas.ogg
sound/barbarossa/lv_neon.wav
sound/barbarossa/palach.mp3
sound/barbarossa/rd_waves.wav
sound/barbarossa/steiner1.mp3
sound/barbarossa/steiner10.mp3
sound/barbarossa/steiner11.mp3
sound/barbarossa/steiner2.mp3
sound/barbarossa/steiner3.mp3
sound/barbarossa/steiner4.mp3
sound/barbarossa/steiner5.mp3
sound/barbarossa/steiner6.mp3
sound/barbarossa/steiner7.mp3
sound/barbarossa/steiner8.mp3
sound/barbarossa/steiner9.mp3
sound/barbarossa/strassenenden.mp3
sound/barbarossa/suicide_shot.ogg
sound/barbarossa/suicide_step.ogg
sound/barbarossa/tankreload2.ogg
sound/barbarossa/tankshoot.ogg
sound/barbarossa/tankstart.ogg
sound/barbarossa/torn_ambience.wav
sound/barbarossa/truck.ogg
sound/barbarossa/yasvoboden.mp3
sound/barbarossa/yazdyes.mp3
sound/weapons/ww2projekt/bazookadeploy.wav
sound/weapons/ww2projekt/bazookapickup.wav
sound/weapons/ww2projekt/bazookareloadgetrocket.wav
sound/weapons/ww2projekt/bazookareloadrocketin.wav
sound/weapons/ww2projekt/bazookareloadshovehome.wav
sound/weapons/ww2projekt/boltback.wav
sound/weapons/ww2projekt/boltforward.wav
sound/weapons/ww2projekt/bren_reload_clipout.wav
sound/weapons/ww2projekt/bulletchain.wav
sound/weapons/ww2projekt/c96_boltrelease.wav
sound/weapons/ww2projekt/c96_clip_in.wav
sound/weapons/ww2projekt/c96_clip_load.wav
sound/weapons/ww2projekt/c96_clip_loadfull.wav
sound/weapons/ww2projekt/c96_clip_out.wav
sound/weapons/ww2projekt/c96_rattle.wav
sound/weapons/ww2projekt/c96_shoot.wav
sound/weapons/ww2projekt/cbar_hit1.wav
sound/weapons/ww2projekt/cbar_hit2.wav
sound/weapons/ww2projekt/colt_empty.wav
sound/weapons/ww2projekt/dp28_reload_clipin1.wav
sound/weapons/ww2projekt/dp28_reload_clipin2.wav
sound/weapons/ww2projekt/dp28_shoot.wav
sound/weapons/ww2projekt/faust_drop.wav
sound/weapons/ww2projekt/fg42_reload_clipin.wav
sound/weapons/ww2projekt/fg42_reload_clipout.wav
sound/weapons/ww2projekt/fg42_shoot1.wav
sound/weapons/ww2projekt/gewehr_reload_clipin.wav
sound/weapons/ww2projekt/gewehr_reload_clipout.wav
sound/weapons/ww2projekt/grenpinpull.wav
sound/weapons/ww2projekt/grenthrow.wav
sound/weapons/ww2projekt/k43_shoot1.wav
sound/weapons/ww2projekt/kar_shoot1.wav
sound/weapons/ww2projekt/knife_hit1.wav
sound/weapons/ww2projekt/knife_hit2.wav
sound/weapons/ww2projekt/knife_hit3.wav
sound/weapons/ww2projekt/knife_hit4.wav
sound/weapons/ww2projekt/knife_hitwall1.wav
sound/weapons/ww2projekt/knife_slash1.wav
sound/weapons/ww2projekt/knife_slash2.wav
sound/weapons/ww2projekt/knifeswing.wav
sound/weapons/ww2projekt/knifeswing2.wav
sound/weapons/ww2projekt/luger_clipin.wav
sound/weapons/ww2projekt/luger_clipout1.wav
sound/weapons/ww2projekt/luger_clipout2.wav
sound/weapons/ww2projekt/luger_shoot1.wav
sound/weapons/ww2projekt/luger_slideback.wav
sound/weapons/ww2projekt/m1885_shoot.wav
sound/weapons/ww2projekt/maxim_reload_bulletchain.wav
sound/weapons/ww2projekt/maxim_reload_chainpull.wav
sound/weapons/ww2projekt/maxim_shoot.wav
sound/weapons/ww2projekt/mg34_magin.wav
sound/weapons/ww2projekt/mg34_magout.wav
sound/weapons/ww2projekt/mg34_shoot1.wav
sound/weapons/ww2projekt/mg42_shoot1.wav
sound/weapons/ww2projekt/mgbolt.wav
sound/weapons/ww2projekt/mgchainpull.wav
sound/weapons/ww2projekt/mgchainpull2.wav
sound/weapons/ww2projekt/mgclampdown.wav
sound/weapons/ww2projekt/mgclampup.wav
sound/weapons/ww2projekt/mgdeploy.wav
sound/weapons/ww2projekt/mgup.wav
sound/weapons/ww2projekt/mosin_shoot.wav
sound/weapons/ww2projekt/mp40_draw_slideback.wav
sound/weapons/ww2projekt/mp40_reload_clipin.wav
sound/weapons/ww2projekt/mp40_reload_clipout.wav
sound/weapons/ww2projekt/mp40_shoot1.wav
sound/weapons/ww2projekt/mp44_draw_slideback.wav
sound/weapons/ww2projekt/mp44_reload_clipin.wav
sound/weapons/ww2projekt/mp44_reload_clipout.wav
sound/weapons/ww2projekt/mp44_shoot1.wav
sound/weapons/ww2projekt/panzerfaust_rocket1.wav
sound/weapons/ww2projekt/ppsh_reload_magin.wav
sound/weapons/ww2projekt/ppsh_reload_magout.wav
sound/weapons/ww2projekt/ppsh_shoot1.wav
sound/weapons/ww2projekt/rifleselect.wav
sound/weapons/ww2projekt/rocket1.wav
sound/weapons/ww2projekt/stripper.wav
sound/weapons/ww2projekt/svt40_reload_boltback.wav
sound/weapons/ww2projekt/svt40_reload_boltforward.wav
sound/weapons/ww2projekt/svt40_reload_clipin.wav
sound/weapons/ww2projekt/svt40_reload_clipout.wav
sound/weapons/ww2projekt/svt40_shoot.wav
sound/weapons/ww2projekt/tokarev_reload_clipin.wav
sound/weapons/ww2projekt/tokarev_reload_clipout.wav
sound/weapons/ww2projekt/tokarev_reload_unlock.wav
sound/weapons/ww2projekt/tokarev_shoot.wav
sound/weapons/ww2projekt/tommy_recharge.wav
sound/weapons/ww2projekt/tommy_reload_clipin.wav
sound/weapons/ww2projekt/tommy_reload_clipin2.wav
sound/weapons/ww2projekt/tommy_reload_slap.wav
sound/weapons/ww2projekt/webley_close.wav
sound/weapons/ww2projekt/webley_cock.wav
sound/weapons/ww2projekt/webley_insert.wav
sound/weapons/ww2projekt/webley_open.wav
sprites/320hud1.spr
sprites/320hud2.spr
sprites/barbarossa/atm_effect.spr
sprites/barbarossa/sp_agua.spr
sprites/barbarossa/sp_agua_h.spr
sprites/barbarossa/spotlight.spr
sprites/ww2projekt/ammo_pfaust.spr
sprites/ww2projekt/ammo_stick.spr
sprites/ww2projekt/german_scope1.spr
sprites/ww2projekt/german_scope4.spr
sprites/ww2projekt/germans_selection.spr
sprites/ww2projekt/soviets_selection.spr
sprites/ww2projekt/weapon_c96.txt
sprites/ww2projekt/weapon_dp28.spr
sprites/ww2projekt/weapon_dp28.txt
sprites/ww2projekt/weapon_fg42.txt
sprites/ww2projekt/weapon_g43.txt
sprites/ww2projekt/weapon_kar98k.txt
sprites/ww2projekt/weapon_kar98kscoped.txt
sprites/ww2projekt/weapon_luger.txt
sprites/ww2projekt/weapon_m1895.txt
sprites/ww2projekt/weapon_maxim.spr
sprites/ww2projekt/weapon_maxim.txt
sprites/ww2projekt/weapon_mg34.spr
sprites/ww2projekt/weapon_mg34.txt
sprites/ww2projekt/weapon_mg42.spr
sprites/ww2projekt/weapon_mg42.txt
sprites/ww2projekt/weapon_mp40.txt
sprites/ww2projekt/weapon_mp44.txt
sprites/ww2projekt/weapon_nagant.txt
sprites/ww2projekt/weapon_nagantscoped.txt
sprites/ww2projekt/weapon_panzerfaust.txt
sprites/ww2projekt/weapon_panzerschreck.txt
sprites/ww2projekt/weapon_ppsh41.txt
sprites/ww2projekt/weapon_rgd33.txt
sprites/ww2projekt/weapon_spade.txt
sprites/ww2projekt/weapon_stick.txt
sprites/ww2projekt/weapon_svt40.txt
sprites/ww2projekt/weapon_tokarev.txt
windwheel.wad
