gfx/env/insurgencybk.bmp
gfx/env/insurgencybk.tga
gfx/env/insurgencydn.bmp
gfx/env/insurgencydn.tga
gfx/env/insurgencyft.bmp
gfx/env/insurgencyft.tga
gfx/env/insurgencylf.bmp
gfx/env/insurgencylf.tga
gfx/env/insurgencyrt.bmp
gfx/env/insurgencyrt.tga
gfx/env/insurgencyup.bmp
gfx/env/insurgencyup.tga
models/bshift/barney_helmet.mdl
models/bshift/barney_vest.mdl
models/pubsec/pubsec_modelreplacement.txt
models/pubsec/weapons/v_9mmar.mdl
models/pubsec/weapons/v_9mmhandgun.mdl
models/pubsec/weapons/v_crowbar.mdl
models/pubsec/weapons/v_m16a2.mdl
models/pubsec/weapons/v_m16.mdl
models/pubsec/weapons/v_shotgun.mdl
models/pubsec/weapons/kimber/p_kimber.mdl
models/pubsec/weapons/kimber/v_kimber.mdl
models/pubsec/weapons/kimber/w_kimber.mdl
models/pubsec_npcs/massn_swat.mdl
models/pubsec_npcs/milita_pistol.mdl
models/pubsec_npcs/milita_pistol1.mdl
models/pubsec_npcs/milita_pistol2.mdl
models/pubsec_npcs/milita_pistol3.mdl
models/pubsec_npcs/milita_pistol4.mdl
models/pubsec_npcs/milita_pistol5.mdl
models/pubsec_npcs/militia_rifle.mdl
models/pubsec_npcs/militia_rifle1.mdl
models/pubsec_npcs/militia_rifle2.mdl
models/pubsec_npcs/militia_rifle3.mdl
models/pubsec_npcs/militia_rifle4.mdl
models/pubsec_npcs/militia_rifle5.mdl
models/pubsec_npcs/scientist_hobo.mdl
models/pubsec_npcs/pedestrians/barney-SDpolice.mdl
models/pubsec_npcs/pedestrians/businessman.mdl
models/pubsec_npcs/pedestrians/businessman01.mdl
models/pubsec_npcs/pedestrians/businessman02.mdl
models/pubsec_npcs/pedestrians/hostage01.mdl
models/pubsec_npcs/pedestrians/hostage02.mdl
models/pubsec_npcs/pedestrians/hostage03.mdl
models/pubsec_npcs/pedestrians/hostage04.mdl
models/pubsec_npcs/pedestrians/hostage05.mdl
models/pubsec_npcs/pedestrians/hostage06.mdl
models/pubsec_npcs/pedestrians/hostage07.mdl
models/pubsec_npcs/pedestrians/hostage08.mdl
models/pubsec_npcs/pedestrians/npc-scientist.mdl
models/pubsec_npcs/pedestrians/npc-scientist01.mdl
models/pubsec_npcs/pedestrians/npc-scientist02.mdl
models/pubsec_npcs/pedestrians/us_gal.mdl
models/pubsec_npcs/pedestrians/us_gal01.mdl
models/pubsec_npcs/pedestrians/us_gal02.mdl
models/pubsec_props/ac_large.mdl
models/pubsec_props/airconditioner.mdl
models/pubsec_props/bathroom_toilet.mdl
models/pubsec_props/bathroom_toilet_dirty.mdl
models/pubsec_props/bathroom_toilet_dirty2.mdl
models/pubsec_props/bathroom_urinal.mdl
models/pubsec_props/bench_locker.mdl
models/pubsec_props/bottle_beer.mdl
models/pubsec_props/bottle_brown.mdl
models/pubsec_props/bottle_scene.mdl
models/pubsec_props/bucket.mdl
models/pubsec_props/bush_evergreen.mdl
models/pubsec_props/bush_fern_small.mdl
models/pubsec_props/bush_fern_small_ground.mdl
models/pubsec_props/bush_japan_bush01.mdl
models/pubsec_props/bush_japan_fern_01.mdl
models/pubsec_props/car_bombed.mdl
models/pubsec_props/car_covered.mdl
models/pubsec_props/car_dealers.mdl
models/pubsec_props/car_hatchback.mdl
models/pubsec_props/car_police.mdl
models/pubsec_props/car_sedan.mdl
models/pubsec_props/car1.mdl
models/pubsec_props/car2.mdl
models/pubsec_props/car3.mdl
models/pubsec_props/car4.mdl
models/pubsec_props/car5.mdl
models/pubsec_props/carpolice.mdl
models/pubsec_props/chair_cafe.mdl
models/pubsec_props/chair_cafe-wood.mdl
models/pubsec_props/chair_cafe-wreck.mdl
models/pubsec_props/chair_folding.mdl
models/pubsec_props/chair_stool.mdl
models/pubsec_props/coke.mdl
models/pubsec_props/coke_bag.mdl
models/pubsec_props/coke_box.mdl
models/pubsec_props/coke_stack.mdl
models/pubsec_props/couch_fabric-wreck.mdl
models/pubsec_props/electrical_box-closed.mdl
models/pubsec_props/flag_us.mdl
models/pubsec_props/foliage_jungle1.mdl
models/pubsec_props/gins_couch.mdl
models/pubsec_props/lamp_citylight_small.mdl
models/pubsec_props/plant_potted.mdl
models/pubsec_props/pot.mdl
models/pubsec_props/power_pole-wood.mdl
models/pubsec_props/stepvan2.mdl
models/pubsec_props/SWAT_van.mdl
models/pubsec_props/table_cafe.mdl
models/pubsec_props/table_cafe-wood.mdl
models/pubsec_props/trash.mdl
models/pubsec_props/trash_02.mdl
models/pubsec_props/trash_heap.mdl
models/pubsec_props/trash_heap-wood.mdl
models/pubsec_props/trash_heep.mdl
models/pubsec_props/trash_trashbag.mdl
models/pubsec_props/trash_trashcan.mdl
models/pubsec_props/trashcan_1_v1.mdl
models/pubsec_props/trashcan_burning.mdl
models/pubsec_props/trashv01.mdl
models/pubsec_props/tree_brownv01.mdl
models/pubsec_props/tree_btrunkv01.mdl
models/pubsec_props/tree_greyv1.mdl
models/pubsec_props/tree_groups.mdl
models/pubsec_props/tree_pine.mdl
models/pubsec_props/tree_plain.mdl
models/pubsec_props/tree_tree2.mdl
models/pubsec_props/tree_tree2a.mdl
models/pubsec_props/tree_tree3.mdl
models/pubsec_props/tree_tree4.mdl
models/pubsec_props/tree_tree5.mdl
models/pubsec_props/tree_tree6.mdl
models/pubsec_props/tree_tree6_2.mdl
models/pubsec_props/tree_tree7.mdl
models/pubsec_props/tree_tree8.mdl
models/pubsec_props/tree_tree9.mdl
models/pubsec_props/tree_tree10.mdl
models/pubsec_props/tree_tree10_2.mdl
models/pubsec_props/treev01.mdl
models/pubsec_props/truck.mdl
models/pubsec_props/truck_flatbed.mdl
models/pubsec_props/truck_large-brown.mdl
models/pubsec_props/truck_large-green.mdl
models/pubsec_props/truck_old.mdl
models/pubsec_props/truck_pickup.mdl
models/pubsec_props/truck_pickup_window.mdl
models/pubsec_props/truck_postage1.mdl
models/pubsec_props/truck_postage2.mdl
models/pubsec_props/truck_snow.mdl
sound/ins2/wpn/m4a1/shoot.ogg
sound/pubsec/ammopickup1.wav
sound/pubsec/ammopickup2.wav
sound/pubsec/c4_plant.wav
sound/pubsec/car_passing.wav
sound/pubsec/caralarm.wav
sound/pubsec/police_on_knees.wav
sound/pubsec/narco/narco_action.wav
sound/pubsec/narco/narco_action_end.wav
sound/pubsec/narco/turncrank_success.wav
sound/pubsec/narco/yourboss_brief_01.wav
sound/pubsec/weapons/pistol-empty.wav
sound/weapons/glock_magin.wav
sound/weapons/glock_magout.wav
sound/pubsec/weapons/mk23/shoot.ogg
sound/weapons/glock_slideforward.wav
sound/doors/door_metal_shake2.wav
sound/ambience/gate_pound.wav
sprites/pubsec/hud/640hud1.spr
sprites/pubsec/hud/640hud4.spr
sprites/pubsec/hud/640hud7.spr
sprites/pubsec/hud/640hudsc2.spr
sprites/pubsec/hud/crosshairs.spr
sprites/pubsec/hud/mk23.spr
sprites/pubsec/hud/weapon_ps_m16.txt
sprites/pubsec/hud/weapon_ps_mk23.txt
sprites/pubsec/hud/weapon_ps_mp5.txt
sprites/pubsec/hud/weapon_ps_spas12.txt
sprites/pubsec_spr/arrow_use.spr